removed duplicate handleExportData
umple/AcademicTeamManagement pull request #191
Opened 2023-09-25 01:36 UTC by RobertBasile-1

### Change Description

### Related PR/Issues, JIRAs

### How to Verify

### Verification
 - [ ] PR/Change is verified in local dev environment

### Tests
 - [ ] Unit tests added/updated
 - [ ] Integration tests added/updated

2023-09-28 23:38 UTC, Akram-El-Gaouny commented
Tested the PR locally, when refreshing the page it downloads multiple copies of the exported data.

2023-09-28 23:43 UTC, Akram-El-Gaouny requested changes

2023-09-28 23:43 UTC, Akram-El-Gaouny commented on client/src/components/ProjectTable/ProjectTable.js
> +                  onClick={handleExportData(tableData,columns, csvExporter)}
```suggestion
                  onClick={ () => handleExportData(tableData,columns, csvExporter)}
```

2023-09-28 23:43 UTC, Akram-El-Gaouny commented on client/src/components/StudentListingView/StudentTable.js
> +              onClick={handleExportData(tableData,columns, csvExporter)}
```suggestion
                  onClick={ () => handleExportData(tableData,columns, csvExporter)}
```

2023-09-28 23:43 UTC, Akram-El-Gaouny commented on client/src/components/GroupView/GroupTable.js
> +              onClick={handleExportData(tableData,columns, csvExporter)}
```suggestion
                  onClick={ () => handleExportData(tableData,columns, csvExporter)}
```

2023-09-29 20:48 UTC, Laith-Grira approved these changes

2023-09-30 15:18 UTC, Akram-El-Gaouny approved these changes

2023-09-30 18:37 UTC, merged